#!/bin/bash
POOL=$1
DS=$2
UPLSNAP=$3
PREVSNAP=$4

simpledb $(cat ~/.zfs_glacier_resumefiles/simpledbcreds) select 'select ARCHIVE_NUMBER from zfsdatasets WHERE dataset="'$DS'" AND poolname="'$POOL'" and snapname="'$UPLSNAP'" and fromsnap="'$PREVSNAP'" and machine="'$(hostname)'" AND ARCHIVE_NUMBER >= "0" ' |xargs -n2 echo |sed 's/^\(.*\) ARCHIVE_NUMBER=\([0-9]*\)$/\1/'
